### ISSUE TITLE
xbib/marc should escape controlfields to make sure the resulting JSON stays valid

### ISSUE THREAD

**Issue by boerni667** [xbib/marc#5]
included controlfields (e.g. tabs) aren't escaped. e.g. if you transform the following record to a json, jq can't read it: "parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 1, column 1442"

[beispiel.mrc.zip](https://github.com/xbib/marc/files/2290236/beispiel.mrc.zip)

**Comment by zazi** [comment]
I guess the unicode escaping in [MarcJsonWriter in marc4j](https://github.com/marc4j/marc4j/blob/d37ccca7ecc63eebc86e69e60ae2f225f52ac230/src/org/marc4j/MarcJsonWriter.java#L369) might be good starting point/or impression. 
re. line-delimited JSON it's not only important to deliver JSON valid content but also line-delimited JSON valid content, e.g., escaped line breaks.

**Comment by zazi** [comment]
implementing a custom MarcValueTransformer won't really lead to the expected result, since [MarcJsonWriter#escape](https://github.com/xbib/marc/blob/master/src/main/java/org/xbib/marc/json/MarcJsonWriter.java#L157) will escape backslashes again and e.g. "\n" will result in "\\n", i.e., I think that all these other special characters also need to be processed via MarcJsonWriter#escape instead of a custom MarcValueTransformer (that will be applied early in the processing chain).

**Comment by jprante** [comment]
Shoud be fixed in MarcJsonWriter
